# Generated by Django 3.2 on 2021-06-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieData', '0002_alter_movieinfo_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='genre',
            field=models.TextField(default='action', max_length=50),
        ),
    ]
